# Generated by Django 4.1.4 on 2022-12-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='writing',
        ),
    ]
