# Generated by Django 4.1.4 on 2022-12-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_rename_article_comment_writing'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='reference_reply_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
