# Generated by Django 4.1.4 on 2022-12-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_remove_comment_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
