# Generated by Django 4.1.4 on 2022-12-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
