# Generated by Django 4.1.4 on 2022-12-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0011_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
