# Generated by Django 4.1.4 on 2022-12-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0012_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
