# Generated by Django 4.1.4 on 2023-01-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0015_user_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='anonymous',
        ),
    ]
