# Generated by Django 4.1.4 on 2023-01-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0016_remove_user_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
